#######################################
#
#       UCB-ACCOUNTING-SYSTEM - v1.0
#
#######################################

version: "3.7"
networks:
  network-uas:
    name: network-uas
    driver: bridge

services:
  uas-postgres-dev:
    container_name: uas-postgres-dev
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PORT: ${POSTGRES_DEV_PORT}
      POSTGRES_USERNAME: ${POSTGRES_DEV_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DEV_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DEV_DB}
      POSTGRES_URL: ${POSTGRES_DEV_URL}
    volumes:
      - ~/Desktop/uas/dev/postgres/data:/var/lib/postgresql/data
      - ./UCB-ACCOUNTING_create.sql:/docker-entrypoint-initdb.d/UCB-ACCOUNTING_create.sql
    networks:
      - network-uas

  uas-keycloak-postgres-dev:
    container_name: uas-keycloak-postgres-dev
    image: postgres
    restart: always
    environment:
      POSTGRES_PORT: ${KEYCLOAK_POSTGRES_DEV_PORT}
      POSTGRES_USERNAME: ${KEYCLOAK_POSTGRES_DEV_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_DEV_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DEV_DB}
      POSTGRES_URL: ${KEYCLOAK_POSTGRES_DEV_URL}
    volumes:
      - ~/Desktop/uas/dev/keycloak/postgres/data:/var/lib/postgresql/data
    networks:
      - network-uas

  uas-keycloak-dev:
    container_name: uas-keycloak-dev
    image: quay.io/keycloak/keycloak:22.0.1
    user: root
    command: start-dev
    restart: always
    ports:
      - "8090:8090"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_DEV_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_DEV_ADMIN_PASSWORD}
      KC_HTTP_PORT: ${KEYCLOAK_DEV_PORT}
      KC_DB: postgres
      KC_DB_URL_HOST: uas-keycloak-postgres-dev
      KC_DB_URL_DATABASE: ${KEYCLOAK_POSTGRES_DEV_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_DEV_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_DEV_PASSWORD}
      KC_DB_SCHEMA: public
    volumes:
      - ~/Desktop/uas/dev/keycloak/data:/opt/keycloak/data
    networks:
      - network-uas
    depends_on:
      - uas-keycloak-postgres-dev

  minio:
    container_name: uas-minio-dev
    image: minio/minio
    user: root
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_DEV_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_DEV_ROOT_PASSWORD}

    volumes:
      - ~/Desktop/uas/dev/minio/data:/data
    command: server /data --console-address ":9090"
    networks:
      - network-uas
  
  uas-backend-dev:
    container_name: uas-backend-dev
    image: thealanmc/uas-backend:0.1.0
    user: root
    ports:
      - "8080:8080"
    environment:
      PORT: ${BACKEND_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
      KEYCLOAK_SERVER_URI: ${KEYCLOAK_SERVER_URI}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      FRONTEND_KEYCLOAK_CLIENT_ID: ${FRONTEND_KEYCLOAK_CLIENT_ID}
      MINIO_SERVER_URI: ${MINIO_SERVER_URI}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ~/Desktop/uas/dev/backend/logs:/opt/uas/logs/uas-backend
    networks:
      - network-uas

