#######################################
#
#       UCB-ACCOUNTING-SYSTEM - v1.0
#
#######################################

version: "3.7"
networks:
  network-uas:
    external: true

services:
  uas-postgres-dev:
    container_name: uas-postgres-development
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PORT: ${POSTGRES_DEV_PORT}
      POSTGRES_USERNAME: ${POSTGRES_DEV_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DEV_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DEV_DB}
      POSTGRES_URL: ${POSTGRES_DEV_URL}
    volumes:
      - ~/Desktop/uas/dev/postgres/data:/var/lib/postgresql/data
      - ./UCB-ACCOUNTING_create.sql:/docker-entrypoint-initdb.d/UCB-ACCOUNTING_create.sql
    networks:
      - network-uas

  uas-postgres-prod:
    container_name: uas-postgres-production
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PORT: ${POSTGRES_PROD_PORT}
      POSTGRES_USERNAME: ${POSTGRES_PROD_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PROD_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PROD_DB}
      POSTGRES_URL: ${POSTGRES_PROD_URL}
    volumes:
      - ~/Desktop/uas/prod/postgres/data:/var/lib/postgresql/data
      - ./UCB-ACCOUNTING_create.sql:/docker-entrypoint-initdb.d/UCB-ACCOUNTING_create.sql
    networks:
      - network-uas

  uas-postgres-test:
    container_name: uas-postgres-test
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PORT: ${POSTGRES_TEST_PORT}
      POSTGRES_USERNAME: ${POSTGRES_TEST_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_URL: ${POSTGRES_TEST_URL}
    volumes:
      - ~/Desktop/uas/test/postgres/data:/var/lib/postgresql/data
      - ./UCB-ACCOUNTING_create.sql:/docker-entrypoint-initdb.d/UCB-ACCOUNTING_create.sql
    networks:
      - network-uas